## CONFIGURATION FILE FOR TESTS ##

##COMMAND LINE TESTS##

RUN_COMMANDLINE_TESTS = True
RUN_SPI_TEST = True
RUN_I2C_TEST = True
RUN_I2C_TOOLS_TEST = True
RUN_PIGPIO_TEST = True 

##INTEGRATION TESTS##

RUN_INTEGRATION_TESTS = True
RUN_MPU6050_I2C_TEST = True

##DEVICE TESTS##

RUN_DEVICE_TESTS = True
RUN_MPU6050_BUILD_TEST = True
RUN_MPU6050_UNITTESTS = True

RUN_SX1278_BUILD_TEST = True
RUN_SX1278_UNITTESTS = True
