RUN_COMMANDLINE_TESTS = True
RUN_SPI_TEST = True
RUN_I2C_TEST = True
RUN_I2C_TOOLS_TEST = True
RUN_PIGPIO_TEST = True 

RUN_INTEGRATION_TESTS = True
RUN_MPU6050_I2C_TEST = True

RUN_DEVICE_TESTS = True
RUN_DEVICE_BUILD_TEST = True
