## CONFIGURATION FILE FOR TESTS ##



##COMMAND LINE TESTS##

RUN_RASP_COMMANDLINE_TESTS = True
RUN_I2C_TOOLS_TEST = True
RUN_PIGPIO_TEST = True 
RUN_SPI_TEST_RASP = True
RUN_I2C_TEST = True

##BUILD TESTS##

RUN_BUILD_TESTS = True
RUN_RASPBERRUY_PI_BUILD_TEST = True

##INTEGRATION TESTS##

RUN_INTEGRATION_TESTS = False
RUN_MPU6050_I2C_TEST = True

##DEVICE TESTS##

RUN_DEVICE_TESTS = True

RUN_MPU6050_TESTS = False
RUN_MPU6050_COMPLIE_TEST = True
RUN_MPU6050_UNITTESTS = True

RUN_SX1278_TESTS = False
RUN_SX1278_COMPLIE_TEST = True
RUN_SX1278_UNITTESTS = True

RUN_DUALSHOCK_TESTS = True
RUN_DUALSHOCK_COMPLIE_TEST = True
RUN_DUALSHOCK_UNITTESTS = True


